=== locate-place/php-location-api/data/json/schema/command/version/resource.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Used for validation of resource.json JSON file.",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "date": {
            "type": "string"
        },
        "license": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "driver-name": {
            "type": "string"
        },
        "environment": {
            "type": "string"
        },
        "php-version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "symfony-version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "composer-version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "doctrine-version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "api-platform-version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        }
    },
    "required": ["version", "date", "license", "authors", "php-version", "symfony-version"],
    "additionalProperties": false
}

=== locate-place/php-location-api/data/json/schema/command/version/resource.json
{
    "$schema": "resource.schema.json",
    "name": "twelvepics-com/php-location-api",
    "description": "Provides a location api.",
    "version": "0.1.14",
    "date": "Monday, July 31, 2023 - 21:50:53",
    "license": "Copyright (c) 2023 Björn Hempel",
    "authors": [
        "Björn Hempel <bjoern@hempel.li>"
    ],
    "driver-name": "PostgreSQL 9.4",
    "environment": "Test",
    "php-version": "8.2.7",
    "symfony-version": "6.3.3",
    "composer-version": "2.5.1",
    "doctrine-version": "2.16.1",
    "api-platform-version": "3.1.14"
}
