=== locate-place/php-location-api/data/json/schema/api/version/resource.valid.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Used for validation of resource.valid.json JSON file.",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "version": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "date": {
            "type": "string"
        },
        "license": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": ["name", "description", "version", "date", "license", "authors"],
    "additionalProperties": false
}

=== locate-place/php-location-api/data/json/schema/api/version/resource.valid.json
{
    "$schema": "resource.valid.schema.json",
    "name": "ixnode/php-api-version-bundle",
    "description": "Provides the base API plattform functionality.",
    "version": "0.1.0",
    "date": "Friday, December 30, 2022 - 09:45:29",
    "license": "Copyright (c) 2022 Björn Hempel",
    "authors": [
        "Björn Hempel <bjoern@hempel.li>"
    ]
}
